#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_FILE="${ROOT}/docker/edopro/EDOPRO_REF.pin"

repo="${EDOPRO_REPO:-https://github.com/diangogav/EDOpro-server-ts.git}"
ref="${1:-${EDOPRO_REF:-main}}"

if ! command -v git >/dev/null 2>&1; then
  echo "error: git not found" >&2
  exit 1
fi

echo "[pin] repo: ${repo}"
echo "[pin] ref:  ${ref}"

sha=""
if [[ "$ref" =~ ^[0-9a-fA-F]{7,40}$ ]]; then
  sha="$ref"
else
  sha="$(git ls-remote "$repo" "$ref" 2>/dev/null | head -n 1 | awk '{print $1}' || true)"
fi
if [ -z "${sha}" ]; then
  echo "error: failed to resolve ref '$ref' from '$repo'" >&2
  echo "hint: run this on a machine with internet access, or pass a full commit SHA (it will be accepted without resolving)." >&2
  exit 2
fi

mkdir -p "$(dirname "$OUT_FILE")"
{
  echo "# Generated by scripts/pin-edopro-ref.sh"
  echo "# $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "EDOPRO_REPO=${repo}"
  echo "EDOPRO_REF=${sha}"
  echo "EDOPRO_REF_ORIGINAL=${ref}"
} >"$OUT_FILE"

echo "[pin] wrote ${OUT_FILE}"
echo "[pin] use:"
echo "      export EDOPRO_REF=${sha}"
